export const data = [
    {
        question: "What does Ghunnah mean?",
        option1: "To Hold",
        option2: "To Bounce",
        option3: "To Stretch",
        option4: "To Hide",
        ans: 1,
    },
    {
        question: "What does Idhaar mean?",
        option1: "To Hold",
        option2: "To Make Clear",
        option3: "To Stretch",
        option4: "To Hide",
        ans: 2,
    },
    {
        question: "What does Ghunnah mean?",
        option1: "To Hold",
        option2: "To Bounce",
        option3: "To Stretch",
        option4: "To Hide",
        ans: 1,
    },
    {
        question: "What does Ghunnah mean?",
        option1: "To Hold",
        option2: "To Bounce",
        option3: "To Stretch",
        option4: "To Hide",
        ans: 1,
    },
    {
        question: "What does Ghunnah mean?",
        option1: "To Hold",
        option2: "To Bounce",
        option3: "To Stretch",
        option4: "To Hide",
        ans: 1,
    },
    {
        question: "What does Ghunnah mean?",
        option1: "To Hold",
        option2: "To Bounce",
        option3: "To Stretch",
        option4: "To Hide",
        ans: 1,
    },
]