export const data = [
    {
        question: "What does Idghaam mean?",
        option1: "To Make Clear",
        option2: "To Bounce",
        option3: "To Merge",
        option4: "To Hide",
        ans: 3,
    },
    {
        question: "What is Idghaam applied to?",
        option1: "Throat Letters",
        option2: "Noon Saakinah and Tanween",
        option3: "Ikhfah",
        option4: "ب",
        ans: 2,
    },
    {
        question: "What are the Idghaam letters??",
        option1:"ينمو",
        option2: "لر",
        option3: "اوي",
        option4: "يرملون",
        ans: 4,
    },
    {
        question: "What are the letters of Idghaam with Ghunnah?",
        option1: "ب",
        option2: "ينمو",
        option3: "يرملون",
        option4: "لر",
        ans: 2,
    },
    {
        question: "What are the letters of Idghaam without Ghunnah?",
        option1: "من يعمل",
        option2:  "ىنمو",
        option3: "لر",
        option4:  "ق",
        ans: 3,
    },
    {
        question: "Choose the example for Idghaam with Ghunnah",
        option1: "من يعمل",
        option2:  " كفوا أحد",
        option3: "لر",
        option4:  "ق",
        ans: 1,
    },
    {
        question: "Choose the example for Idghaam without Ghunnah",
        option1: "سميع عليم",
        option2:  "ىنمو",
        option3: "من يعمل",
        option4:  "من رّبّك",
        ans: 4,
    },

]